### PR TITLE
Remove reference to L.Mixin.Evented

### PR DESCRIPTION
**Pull request by csxphil**
To be compatible with Leaflet 1.2.0, added ability to use the L.Evented instead.

### CODE REVIEW

**Comment by Turbo87** [comment]
@csxphil can you link me to the docs about the deprecation of `L.Mixin.Events`?

**Comment by csxphil** [comment]
Thanks for taking the time to look into this!

https://github.com/Leaflet/Leaflet/issues/2280

**Comment by Turbo87** [comment]
thanks :)

**Comment by ogix** [comment]
Can you release a new version? Thanks!

**Comment by Turbo87** [comment]
> Can you release a new version?

`v0.4.0` should be available via npm and Bower now.

**Comment by ogix** [comment]
Wow that was pretty fast. Thanks again!

**Pull request merged**
