### PR TITLE
Fix conflict with close function

### PR DESCRIPTION
**Pull request by lucawen**
When use 'close' function on map click, the 'open' function doesn't work with Layer multipolygon

### CODE REVIEW

**Comment by Turbo87** [comment]
I don't understand what issue this is trying to fix and I have doubts that inserting a random `setTimeout()` is actually the correct fix for anything... 🤔

**Comment by lucawen** [comment]
Maybe you can reproduce what happened ...

When you add a GeoJson, for example, on the map, where its features are multipolygon, and a click event is added to the map to close,

Example:
```
Map.on ('click', function () {
   Sidebar.close ();
});

```
And adds a click event in the geojson to open the sidebar, it does not open, because when opening, the previous event of closing is executed, ie it is as if nothing happened ... If you put the timeout of 1ms, it closes, And then opens. Maybe more complex control can solve the problem. This was a quick fix (but not the best), so sorry for that.

**Comment by Turbo87** [comment]
my guess is that you can probably use something like https://developer.mozilla.org/en-US/docs/Web/API/Event/stopPropagation to prevent the `sidebar.close()` callback from running. I don't think that this is something that this lib should handle. Thanks for the PR anyways! 👍

**Comment by lucawen** [comment]
So sorry for that... but thanks 👍

**Pull request closed without merging**
